# Generated by Django 5.1.5 on 2025-02-21 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_user_id_user_role_user_uuid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
